### ISSUE TITLE
request to publish a new version

### ISSUE THREAD

**Issue by HurSungYun** [mroth/weightedrand#7]
Hello.

I'm using this library and found there was a bug patch recently. (https://github.com/mroth/weightedrand/pull/6)

Can you please release new version when you have time?

thanks in advance

**Comment by mroth** [comment]
If there is demand, I'll do it right now!

**Comment by mroth** [comment]
Resolved in `v0.4.1`.

**Comment by HurSungYun** [comment]
really appreciated :)
